# This is a basic workflow to help you get started with Actions

name: Ready_API_Test_Updt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: Ready_API_Test_Updt
        working-directory: 'C:\Users\eatcsud\AppData\Local\Programs\SmartBear\ReadyAPI-3.49.0\bin>'
        run: 'C:\Users\eatcsud\AppData\Local\Programs\SmartBear\ReadyAPI-3.49.0\bin\testrunner.bat -r -a -j -f${WORKSPACE} "-RJUnit-Style HTML Report" -FXML "-EDefault environment" C:\Ranam_Srinivas\Detect-Language-API-readyapi-project'

     
