# This is a basic workflow to help you get started with Actions

name: Run ReadyAPI tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Download and install ReadyAPI
        run: |
          wget -O ReadyAPI.tar.gz https://smartbear.com/product/ready-api/free-trial/thank-you/?fid=91&id=R834323147438SLM ReadyAPI.tar.gz -C /desired/installation/path

      - name: Run ReadyAPI tests
        run: |
         C:\Program Files\SmartBear\ReadyAPI-3.44.0\bin\testrunner.bat" -r -a -j -f${WORKSPACE} "-RJUnit-Style HTML Report" -FXML "-EDefault environment" "H:\Srinivas\Personal Project\New folder\Detect-Language-API-readyapi-project

