name: Run ReadyAPI Tests

on:
 workflow_dispatch

jobs:
  execute-test:
    runs-on: self-hosted

    steps:
      - name: Run ReadyAPI Tests
        working-directory: 'C:\Users\eatcsud\AppData\Local\Programs\SmartBear\ReadyAPI-3.49.0\bin>'
        run: 'C:\Users\eatcsud\AppData\Local\Programs\SmartBear\ReadyAPI-3.49.0\bin\testrunner.bat -sSingleDetectionPostiveandNegative -r -a -j -f${WORKSPACE} "-RJUnit-Style HTML Report" -FXML "-EDefault environment" C:\Ranam_Srinivas\Detect-Language-API-readyapi-project'
          
