name: Run ReadyAPI Tests

on:
  push:
    branches: [main] # Modify this based on your branch setup

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run ReadyAPI Tests
        run: |
          # Run your ReadyAPI tests here
          # Example command:
          # readyapi.sh -f /path/to/your/project.xml -R "JUnit-Style HTML Report" -O "/path/to/output/folder"

      # You might want to add steps to upload test reports, artifacts, etc.
